const DepartmentList = [
  'Aeronautical and Aerospace Engineering',
  'Architectural Engineering',
  'Systems and Biomedical Engineering',
  'Chemical Engineering',
  'Computer Engineering',
  'Electrical Power Engineering',
  'Electronic and Electrical Communications Engineering',
  'Civil Engineering',
  'Mechanical Design and Production',
  'Mechanical Power Engineering',
  'Mining & Geological Engineering Program',
  'Petroleum Engineering Program',
  'Metallurgical Engineering Program',
  'Communication and Computer Engineering (CCE)',
  'Construction Engineering and Management (CEM)',
  'Structural Engineering (STE)',
  'Architectural Engineering and Technology (AET)',
  'Petroleum and Petrochemical Engineering (PPC)',
  'Mechanical Design Engineering (MDE)',
  'Electrical Energy Engineering (EEE)',
  'Civil Infrastructure Engineering (CIE)',
  'Aeronautical Engineering & aviation Management (AEM)',
  'Mechatronics Engineering (MEE)',
  'Biomedical Data Engineering (BDE)',
  'Industrial Engineering & Management (IEM)',
  'Manufacturing Engineering & Materials (MEM)',
  'Sustainable Energy Engineering (SEE)',
  'Water Engineering and Environment (WEE)',
  'Preparatory year',
];

export default DepartmentList;
